language: go
go: "1.10"
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/goimports
  - go install golang.org/x/tools/cmd/goimports
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/aryann/difflib
  - go get github.com/grsmv/inflect
  - go get github.com/hjson/hjson-go
  - go get github.com/mitchellh/mapstructure
  
script:
  - cd gengen
  - go test -v -covermode=count -coverprofile=profile.cov -coverpkg=github.com/runner-mei/gogen/gengen  ./...
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken=$COVERALLS_TOKEN -v -show

env:
  global:
    secure: N3DaOmCbZS46jriOkMzSexVs+agk8YkdCoZbYUmDEYLjXv0EdXvKYiRqbgeLPIizBvQxJgJjXu8x2qV4E+nlXKgZivZe+fiFuXci2HqDNnzcK5VeUwBwaMLLkwpxlgymQGJdTmOtZsdlKByfT/lhzFVnketUlBNubC8ykpMxHntYd8GFJawSL2Y5pdJquqqey2dfhZ+alcSuYWKiX4RCN/9XGDRu+WCXiS/CxzHCs8XCPppuJjcZKMio6T1qjkO1WEQT3Uxepk0f+iUmMw/BwDeFvxABdQUsSWm4Vy4Or3q+efU1w8XjYxt+eBAjm16T3EU2l05wir5a6fS/UiDpgjon484ZPrrZ+1qKcKCd91lx24+jB71An4WsZDiqErroh5eOSv5gWWG3/1lah+w4CI7bN5TVhY/mILba+S/xAchn18dyffhv34I5cXnDjqVJiNqZHpoxk9YuLAYOgE6/X7HvYr+ON1buq07KJYdpFmQZaaLZcGyXsf9VvAf7AYX7Zs8xb/+DuKKGgBOFJHUU4Piwu9kboak0xHAAGkszwHR0L/NoItqaivmlyg2JYQ8ID2E0rxRhSj3S1HmWSpKfkfkvV6ftJG+FbMrKqH42F35LXwG9Wp3WnNzwxazMgg/jwXaDPKb3IJmBtfD5uGP3wl5PDlLHWMZGOm903LIFSw8=