name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: preinstall
        run: |
            go env
            go install golang.org/x/tools/cmd/goimports
            go install github.com/mattn/goveralls

      - name: Test
        run: |
           pwd
           go test -v -covermode=count -coverprofile=profilev1.cov -coverpkg=github.com/runner-mei/gogen/v1/gengen  ./v1/gengen
           go test -v -covermode=count -coverprofile=profilev2.cov -coverpkg=github.com/runner-mei/gogen/v2/gengen  ./v2/gengen
           goveralls -coverprofile=profilev1.cov,profilev2.cov -service=github -v -show
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}